### ISSUE TITLE
[IMPROVE] Contact Page - Redesign and new features

### ISSUE THREAD

**Issue by zourite** [zourite/ssaugrin#11]
Give to visitor an easy way to follow me on social media and get in touch with me.

## Targets

- [ ]  Improve UI/UX
- [ ]  Add a contact form
- [ ]  Add useful links section
